version: "3.9"

services:
  main:
    container_name: misabot-discord
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      TOKEN: <token here>
    expose:
      - 5000
    networks:
      - common

networks:
  common:
